### PR TITLE
client/pkg/v3: fixes Solaris build of transport

### LINKED ISSUE #13298: etcd go client fails to compile for Solaris
I'm compiling the go client library for Solaris and I get following error

```
../../go/pkg/mod/go.etcd.io/etcd/client/pkg/v3@v3.5.0/transport/sockopt_unix.go:14:54: undefined: unix.SO_REUSEPORT
```

The change was introduced in https://github.com/etcd-io/etcd/pull/12702.

Apparently `SO_REUSEPORT` is missing on Solaris.  Should there be build constraint for that socket option?

### PR DESCRIPTION
**Pull request by tsaarni**
Add empty implementation for reuse port socket option since Solaris does not
support SO_REUSEPORT.

Fixes #13298

### CODE REVIEW

**Review by ptabor — APPROVED** [review]
Thank you.

**Comment by tsaarni** [comment]
Are these test failures because of flakiness? Can't figure out the relation to the change.

**Comment by tsaarni** [comment]
Are these test failures caused by #12993? 

I found failures consistently reported for `TestKVWithEmptyValue` in various runs recently, not just this PR. See for example couple of latest runs in main branch https://github.com/etcd-io/etcd/commits/main

The [workflow](https://github.com/etcd-io/etcd/blob/884e7ddb14b0900eac78d81d27d195d9fd63f37d/.github/workflows/tests.yaml#L19) sets `go-version: "^1.16"` which now will pick 1.17 as seen from the logs:
```
2021-09-08T20:09:31.5800695Z ##[group]Run actions/setup-go@v2
2021-09-08T20:09:31.5801791Z with:
2021-09-08T20:09:31.5802145Z   go-version: ^1.16
2021-09-08T20:09:31.5802821Z   stable: true
2021-09-08T20:09:31.5803874Z   token: ***
2021-09-08T20:09:31.5804455Z ##[endgroup]
2021-09-08T20:09:31.6407172Z Setup go stable version spec ^1.16
2021-09-08T20:09:31.6473905Z Found in cache @ /opt/hostedtoolcache/go/1.17.0/x64
2021-09-08T20:09:31.6486536Z Added go to the path
2021-09-08T20:09:32.4457341Z Successfully setup go version ^1.16
2021-09-08T20:09:32.4528617Z go version go1.17 linux/amd64
```

Apparently the correct syntax for staying on go1.16.x would be `go-version: "1.16"`.  The syntax that the action uses [this](https://www.npmjs.com/package/semver) and it is possible to see the matcher in action in [here](https://semver.npmjs.com/).

**Comment by tsaarni** [comment]
cc @lilic

**Comment by tsaarni** [comment]
@ptabor, @spzala I've merged the fix from main, could you approve the workflows for yet another round? Thanks!

**Review by spzala — APPROVED** [review]
lgtm
Thanks @tsaarni

**Review by lilic — APPROVED** [review]
lgtm, thank you!

Tests pass so this should be ready to go I think.

**Comment by tsaarni** [comment]
Kindly asking if it would be possible to get this PR merged? Thanks!
