### PR TITLE
[test] Fix test code compiling error due to not enough arguments 

### PR DESCRIPTION
**Pull request by ahrtr**
Pipeline error caused by https://github.com/etcd-io/etcd/commit/70de5c8937b3ffc045afa1e12b89d2beb107d98e

```
stderr: go: downloading golang.org/x/sync v0.0.0-20220601150217-0de741cfad7f
stderr: # go.etcd.io/etcd/tests/v3/e2e
Error: stderr: vet: e2e/ctl_v3_auth_test.go:1404:26: not enough arguments in call to node0.Restart
FAIL: (code:2):
  % (cd tests && 'go' 'vet' './...')

FAIL: 'run go vet ./...' checking failed (!=0 return code)
FAIL: 'govet' failed at Tue Aug 30 03:07:13 UTC 2022
```

Refer to https://github.com/etcd-io/etcd/runs/8083906786?check_suite_focus=true

Signed-off-by: Benjamin Wang <wachao@vmware.com>

cc @serathius @spzala @ptabor 

I will update the CI to add build for the test code in a separate PR.

### CODE REVIEW

**Comment by ahrtr** [comment]
Found the issue when working on https://github.com/etcd-io/etcd/pull/14400

**Comment by ahrtr** [comment]
One more error,

```
DONE 1 tests in 0.001s
Saved JUnit XML test report to /home/runner/work/etcd/etcd/linux-386-unit-1-cpu/junit_MTY2MTgzNjI4Ngo.xml
% (cd tests && 'env' 'ETCD_VERIFY=all' 'go' 'test' '-v' '-json' '-short' '-timeout=3m' '--race=false' '--cpu=1' './...' '-p=4')
stderr: go: downloading golang.org/x/sync v0.0.0-20220601150217-0de741cfad7f
stderr: # go.etcd.io/etcd/tests/v3/e2e [go.etcd.io/etcd/tests/v3/e2e.test]
Error: stderr: e2e/no_quorum_ready_test.go:34:21: not enough arguments in call to epc.Start
stderr: have ()
stderr: want (context.Context)
```

Refer to https://github.com/etcd-io/etcd/runs/8084995160?check_suite_focus=true

**Review by serathius — APPROVED** [review]

**Review by spzala — COMMENTED** [review]
lgtm Thanks @ahrtr
