### ISSUE TITLE
e2e:TestV3CurlAuth failure

### ISSUE THREAD

**Issue by xiang90** [etcd-io/etcd#10806]
```
--- FAIL: TestV3CurlAuth (1.45s)
    v3_curl_test.go:203: failed testV3CurlAuth add user with curl (read /dev/ptmx: input/output error (expected "revision", got ["curl: (52) Empty reply from server\r\n"]))
    ctl_v3_test.go:168: error closing etcd processes (exit status 2)
=== RUN   TestV3CurlAuthClientTLSCertAuth
--- FAIL: TestV3CurlAuthClientTLSCertAuth (1.01s)
    v3_curl_test.go:203: failed testV3CurlAuth add user with curl (read /dev/ptmx: input/output error (expected "revision", got ["curl: (56) Unexpected EOF\r\n"]))
    ctl_v3_test.go:168: error closing etcd processes (exit status 2)
```

**Comment by jingyih** [comment]
In which PR did you see these? They should be fixed by #10800.

**Comment by xiang90** [comment]
@jingyih 

this one https://github.com/etcd-io/etcd/pull/10803

**Comment by jingyih** [comment]
Just checked, the code in #10803 does not have the fix introduced by #10800.

Ref: https://github.com/tbg/etcd/blob/cbb7730c26ab4d442a34ce7b31273701ee3b1407/tests/e2e/v3_curl_test.go#L199

**Comment by xiang90** [comment]
thanks
