### ISSUE TITLE
etcd go client fails to compile for Solaris

### ISSUE THREAD

**Issue by tsaarni** [etcd-io/etcd#13298]
I'm compiling the go client library for Solaris and I get following error

```
../../go/pkg/mod/go.etcd.io/etcd/client/pkg/v3@v3.5.0/transport/sockopt_unix.go:14:54: undefined: unix.SO_REUSEPORT
```

The change was introduced in https://github.com/etcd-io/etcd/pull/12702.

Apparently `SO_REUSEPORT` is missing on Solaris.  Should there be build constraint for that socket option?
