### ISSUE TITLE
etcd/client/v3 error

### ISSUE THREAD

**Issue by 1231sadqwf** [etcd-io/etcd#12569]
after go get  go.etcd.io/etcd/client/v3, it show this error

# go.etcd.io/etcd/client/v3/balancer/picker
go/src/go.etcd.io/etcd/client/v3/balancer/picker/err.go:25:9: cannot use &errPicker literal (type *errPicker) as type Picker in return argument:
        *errPicker does not implement Picker (wrong type for Pick method)
                have Pick(context.Context, balancer.PickInfo) (balancer.SubConn, func(balancer.DoneInfo), error)
                want Pick(balancer.PickInfo) (balancer.PickResult, error)
go/src/go.etcd.io/etcd/client/v3/balancer/picker/roundrobin_balanced.go:33:9: cannot use &rrBalanced literal (type *rrBalanced) as type Picker in return argument:
        *rrBalanced does not implement Picker (wrong type for Pick method)
                have Pick(context.Context, balancer.PickInfo) (balancer.SubConn, func(balancer.DoneInfo), error)
                want Pick(balancer.PickInfo) (balancer.PickResult, error)

**Comment by SunSince90** [comment]
I had experienced this as well, and I think was caused by #12527 

I fixed it with this in `go.mod`:

```go

require (
	go.etcd.io/etcd v0.5.0-alpha.5.0.20200910180754-dd1b699fc489
	google.golang.org/genproto v0.0.0-20201210142538-e3217bee35cc
	google.golang.org/grpc v1.34.0
)

replace (
	github.com/coreos/etcd => github.com/coreos/etcd v3.3.13+incompatible
	go.etcd.io/bbolt => go.etcd.io/bbolt v1.3.5
	go.etcd.io/etcd => go.etcd.io/etcd v0.5.0-alpha.5.0.20200910180754-dd1b699fc489 // ae9734ed278b is the SHA for git tag v3.4.13
	google.golang.org/grpc => google.golang.org/grpc v1.27.1
)
```

Let me know if this works for you, maybe there is some other imports I forgot. By the way, this is only a workaround of course, we gott wait for the team to fix it with the latest version :)

**Comment by cleverlzc** [comment]
same issue, tricky...

**Comment by cleverlzc** [comment]
Multiple third-party libraries depend on etcd and are of different versions. If different etcd versions are incompatible(for exmaple, v3.4.9 and v3.5.3/4), a conflict occurs and an error is reported. To solve this problem, upgrade the upper-layer third-party libraries to synchronize etcd versions.

**Comment by cleverlzc** [comment]
another solution：
```
replace google.golang.org/grpc => google.golang.org/grpc v1.29.1（or v1.26.0）
```

for old etcd，grpc icompatible， for lastest etcd，grpc compatible（clientv3 not equeal client/v3）
